2024-01-11 14:34:04,558 - INFO - |------------------------- Running Step 0 -------------------------|
2024-01-11 14:34:44,074 - INFO - Processing GHCN Data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1453589/1453589 [00:07<00:00, 259485.97it/s]
2024-01-11 14:35:10,744 - INFO - |------------------------- Running Step 1 -------------------------|
2024-01-11 14:35:11,922 - INFO - Removing faulty data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 81.18it/s]
2024-01-11 14:35:11,923 - INFO - Number of data points removed: 12956
2024-01-11 14:35:30,384 - INFO - |------------------------- Running Step 2 -------------------------|
2024-01-11 14:35:50,775 - INFO - Calculating distances between all grid point/station pairs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 16022/16022 [00:19<00:00, 824.11it/s]
2024-01-11 14:39:44,118 - INFO - |------------------------- Running Step 3 -------------------------|
2024-01-11 14:43:39,352 - INFO - |------------------------- Running Step 4 -------------------------|
2024-01-11 14:47:37,959 - INFO - Calculating distances between all grid point/station pairs: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 11240/11240 [00:07<00:00, 1499.89it/s]
2024-01-11 14:54:19,354 - INFO - |------------------------- Running Step 5 -------------------------|
2024-01-11 14:55:53,772 - ERROR - An error occurred: found the following matches with the input file in xarray's IO backends: ['netcdf4', 'h5netcdf']. But their dependencies may not be installed, see:
https://docs.xarray.dev/en/stable/user-guide/io.html 
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
Traceback (most recent call last):
  File "/Users/mjhendri/Documents/Gitworkspace/GISTEMP_rewrite/GISTEMP_rewrite/main/run.py", line 110, in main
    step5_output = step5.step5(
                   ^^^^^^^^^^^^
  File "/Users/mjhendri/Documents/Gitworkspace/GISTEMP_rewrite/GISTEMP_rewrite/steps/step5.py", line 198, in step5
    da = sst_dataset(url=ERSST_URL, start=START_DATE, end=END_DATE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjhendri/Documents/Gitworkspace/GISTEMP_rewrite/GISTEMP_rewrite/steps/step5.py", line 57, in sst_dataset
    da_ocean = xr.open_dataset(local_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjhendri/anaconda3/lib/python3.11/site-packages/xarray/backends/api.py", line 547, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjhendri/anaconda3/lib/python3.11/site-packages/xarray/backends/plugins.py", line 197, in guess_engine
    raise ValueError(error_msg)
ValueError: found the following matches with the input file in xarray's IO backends: ['netcdf4', 'h5netcdf']. But their dependencies may not be installed, see:
https://docs.xarray.dev/en/stable/user-guide/io.html 
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
